/**
 * Type definitions for the RAG application.
 */

// Represents a chunk of text extracted from the PDF document
export interface TextChunk {
  id: string;
  pageNumber: number;
  content: string;
  charCount: number;
  tokenCount?: number;
}

// Data payload structure produced by Phase 2 Chunking saved in data/chunks.json
export interface ChunkedDocument {
  sourceFilename: string;
  totalChunks: number;
  chunkSizeTokens: number;
  chunkOverlapTokens: number;
  chunkedAt: string;
  chunks: TextChunk[];
}

// Represents a single page extracted from a PDF document
export interface ExtractedPage {
  page: number;
  text: string;
}

// Full JSON data structure produced by PDF extraction in Phase 1
export interface ExtractedDocument {
  filename: string;
  totalPages: number;
  extractedAt: string;
  pages: ExtractedPage[];
}

// Represents a text chunk paired with its numerical vector embedding generated by nomic-embed-text
export interface VectorEmbedding {
  id: string;
  chunkId: string;
  content: string;
  embedding: number[]; // Array of floating-point numbers representing semantic vector
  pageNumber: number;
}

// Data payload structure stored in data/store.json or data/vectors.json
export interface LocalVectorStore {
  updatedAt: string;
  totalChunks: number;
  vectors: VectorEmbedding[];
}

// API Request format for querying RAG
export interface QueryRequest {
  question: string;
}

// API Response format for RAG answer generation
export interface QueryResponse {
  answer: string;
  retrievedChunks: {
    content: string;
    pageNumber: number;
    score: number; // Cosine similarity score
  }[];
}
