/**
 * Type definitions for the RAG application.
 */

// Represents a chunk of text extracted from the PDF document
export interface TextChunk {
  id: string;
  pageNumber: number;
  content: string;
  charCount: number;
  tokenCount?: number;
}

// Data payload structure produced by Phase 2 Chunking saved in data/chunks.json
export interface ChunkedDocument {
  sourceFilename: string;
  totalChunks: number;
  chunkSizeTokens: number;
  chunkOverlapTokens: number;
  chunkedAt: string;
  chunks: TextChunk[];
}

// Represents a single page extracted from a PDF document
export interface ExtractedPage {
  page: number;
  text: string;
}

// Full JSON data structure produced by PDF extraction in Phase 1
export interface ExtractedDocument {
  filename: string;
  totalPages: number;
  extractedAt: string;
  pages: ExtractedPage[];
}

// Represents a text chunk paired with its numerical vector embedding generated by nomic-embed-text
export interface VectorEmbedding {
  id: string;
  chunkId: string;
  content: string;
  embedding: number[]; // Array of floating-point numbers representing semantic vector
  pageNumber: number;
}

// Data payload structure stored in data/store.json or data/vectors.json
export interface LocalVectorStore {
  filename?: string;
  sourceFilename?: string;
  embeddingModel?: string;
  dimensions?: number;
  updatedAt?: string;
  totalChunks?: number;
  totalVectors?: number;
  vectors: VectorEmbedding[];
}

// Represents a single turn in a chat conversation
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
  sources?: { file: string; page: number }[];
}

// API Request format for querying RAG
export interface QueryRequest {
  question: string;
  topK?: number;
  chatHistory?: ChatMessage[];
}

// API Response format for RAG answer generation
export interface QueryResponse {
  success: boolean;
  question: string;
  modelUsed: string;
  answer: string;
  sources?: { file: string; page: number }[];
  retrievedChunks: {
    chunkId: string;
    content: string;
    pageNumber: number;
    score: number; // Cosine similarity score
  }[];
  constructedPrompt?: string;
  chatHistory?: ChatMessage[];
  error?: string;
}

